const projects = [
  {
    id: 1,
    title: "Alchemist Verena",
    description:
      "In a world ablaze with mystic wonders, an adventurous alchemist emerges from the shadows, her spirit aflame with a relentless pursuit of arcane secrets. With her satchel filled with vials and her eyes brimming with curiosity, she traverses untamed landscapes, unearthing rare herbs and exotic ingredients to fuel her daring transmutations. Guided by an insatiable hunger for knowledge, she dances on the precipice of discovery, forever driven to unlock the mysteries that lie hidden within the alchemical arts.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-alchemist-verena.jpg",
    tools: ["Photoshop", "Wacom Intuos Pro"],
    tags: ["Illustration", "Character Design"],
  },
  {
    id: 2,
    title: "Jeera",
    description:
      "Portrait of the travelling merchant known as Jeera. Every spring he sets off on a long journey accross the Iron Straits to provide the locals with goods they've never seen before and more often than not - ones they don't at all need.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-jeera-mihaylov.jpg",
    tools: ["Photoshop", "Wacom Intuos Pro"],
    tags: ["Illustration", "Character Design"],
    additionalImages: [
      "/images/illustration_images/mihail-mihaylov-jeera-lineart-mihaylov.jpg",
    ],
  },
  {
    id: 3,
    title: "Sacrificial Dagger",
    description:
      "A collection of illustrated characters exploring themes of technology and human connection.",
    category: "illustration",
    image:
      "/images/illustration_images/mihail-mihaylov-ceremonial-dagger-mihaylovlr.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design"],
  },
  {
    id: 4,
    title: "Gift It",
    description:
      "Giftit is a webapp, which helps the user select the right gift, create events and invite friends to them and make use of the birthday calendar feature.",
    category: "development",
    image: "/images/development_images/giftit1.jpg",
    link: "https://github.com/tielass/giftit",
    tools: [
      "Ruby on Rails",
      "Javascript",
      "HTML5",
      "CSS3",
      "Figma",
      "PostgreSQL",
    ],
    tags: [
      "WebApp",
      "FullStack Development",
      "Frontend Development",
      "UI/UX Design",
    ],
    additionalImages: [
      "/images/development_images/giftit2.jpg",
      "/images/development_images/giftit3.jpg",
      "/images/development_images/giftit4.jpg",
      "/images/development_images/giftit5.jpg",
      "/images/development_images/giftit6.jpg",
    ],
    thumbnailDimensions: { height: "80px", width: "40px" },
    figmaLink:
      "https://www.figma.com/embed?embed_host=share&amp;url=https%3A%2F%2Fwww.figma.com%2Fproto%2F4VW4XZ1OqAKcLCuLvyrRIf%2FLe-Wagon-GiftIt-Master%3Fpage-id%3D0%253A1%26type%3Ddesign%26node-id%3D935-2598%26viewport%3D-4%252C229%252C0.14%26t%3DrB0GBdYCoCYIfI2o-1%26scaling%3Dscale-down%26starting-point-node-id%3D935%253A2598%26mode%3Ddesign",
  },
  {
    id: 5,
    title: "SpaceX Monitoring",
    description:
      "A website that provides information about SpaceX launches, including launch dates, rocket types, and mission details. Users can filter launches by year and rocket type. The site is designed with the space-x api https://github.com/r-spacex/SpaceX-API",
    category: "development",
    image: "/images/development_images/space-x-monitoring-5.jpg",
    link: "https://spacexmonitoring.netlify.app/",
    tools: ["React", "Javascript", "HTML5", "CSS3", "Figma", "SpaceX API"],
    tags: ["SpaceX", "WebApp", "Frontend Development"],
    additionalImages: [
      "/images/development_images/space-x-monitoring-1.jpg",
      "/images/development_images/space-x-monitoring-2.jpg",
      "/images/development_images/space-x-monitoring-3.jpg",
    ],
    thumbnailDimensions: { height: "150px", width: "150px" },
  },
  {
    id: 6,
    title: "Pre-Employment Screening Portal",
    description: `Developed a responsive pre-employment screening portal that streamlines candidate background checks, document uploads. Integrated secure authentication, intuitive dashboards, and dynamic form components using modern frontend frameworks for a seamless user experience.\nDue to the confidential nature of the project, specific details and functionalities cannot be publicly disclosed.`,
    category: "development",
    image: "/placeholder.svg",
    tools: [
      "NextJs",
      "Figma",
      "React",
      "NextAuth",
      "RestAPI",
      "SSO",
      "Azure-AD",
      "MUI DataGrid",
      "Recharts",
    ],
    tags: ["Frontend development", "WebApp", "UI/UX Design", "NextJs", "React"],
  },
  {
    id: 7,
    title: "Gym Equipment Icons",
    description: "A set of icons for gym equipment.",
    category: "design",
    image: "/images/visual_design_images/gym-equipment-mihaylov.jpg",
    tools: ["Illustrator", "Procreate"],
    tags: ["Visual Elements", "Icon Design", "2D Art"],
    additionalImages: [],
  },
  {
    id: 8,
    title: "Beverages Icons",
    description: "A set of icons for beverages.",
    category: "design",
    image: "/images/visual_design_images/alcohol-mihaylov.jpg",
    tools: ["Illustrator", "Procreate"],
    tags: ["Visual Elements", "Icon Design", "2D Art"],
    additionalImages: [],
  },
  {
    id: 9,
    title: "Coffee Beans Logo",
    description: "Logo for a coffee and breakfast place.",
    category: "design",
    image: "/images/visual_design_images/coffeebeans-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Logo", "Brand Identity", "2D Art"],
    additionalImages: [],
  },
  {
    id: 10,
    title: "Free Delivery",
    description: "Banner for a free delivery campaign.",
    category: "design",
    image: "/images/visual_design_images/truck-mihaylov-240x400.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Visual Elements", "Banner Design", "2D Art"],
    additionalImages: [
      "/images/visual_design_images/truck-mihaylov-500x500.jpg",
      "/images/visual_design_images/truck-mihaylov-1.jpg",
      "/images/visual_design_images/truck-mihaylov-120x600.jpg",
      "/images/visual_design_images/truck-mihaylov-160x600.jpg",
    ],
    thumbnailDimensions: { height: "80px", width: "auto" },
  },
  {
    id: 11,
    title: "Nature Meets Skin",
    description:
      'Logo for a skin care series with all natural products "Nature Meets Skin".',
    category: "design",
    image: "/images/visual_design_images/nature-logo-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Logo", "Brand Identity", "2D Art"],
    additionalImages: [
      "/images/visual_design_images/nms1.jpg",
      "/images/visual_design_images/nms2.jpg",
      "/images/visual_design_images/nms3.jpg",
    ],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 12,
    title: "Somnofy",
    description: "Logo for a sleep tracking app.",
    category: "design",
    image: "/images/visual_design_images/somnofy-2-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Logo", "App Design", "Brand Identity"],
    additionalImages: ["/images/visual_design_images/somnofy-1-mihaylov.jpg"],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 13,
    title: "Omega",
    description: "Logo for a men's watch company.",
    category: "design",
    image: "/images/visual_design_images/omega-logo-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Logo", "Brand Identity", "2D Art"],
    additionalImages: [],
  },
  {
    id: 14,
    title: "Birds",
    description: "A contestant for a logo design for a bird watching app.",
    category: "design",
    image: "/images/visual_design_images/birds-logo-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Logo", "App Design", "Brand Identity"],
    additionalImages: [],
  },
  {
    id: 15,
    title: "Vintage Gym",
    description: "Poster for a vintage gym event.",
    category: "design",
    image: "/images/visual_design_images/vintage-gym-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop"],
    tags: ["Visual Elements", "Poster Design", "2D Art"],
    additionalImages: [],
  },
  {
    id: 16,
    title: "Africa Endangered Species",
    description:
      "An infographic for endangered species in Africa. The information is relevant as of 2016.",
    category: "design",
    image: "/images/visual_design_images/africa-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop", "Data Visualization"],
    tags: ["Visual Elements", "Infographic", "2D Art"],
    additionalImages: [],
  },
  {
    id: 17,
    title: "Asia Endangered Species",
    description:
      "An infographic for endangered species in Asia. The information is relevant as of 2016.",
    category: "design",
    image: "/images/visual_design_images/asia-mihaylov.jpg",
    tools: ["Illustrator", "Photoshop", "Data Visualization"],
    tags: ["Visual Elements", "Infographic", "2D Art"],
    additionalImages: [],
  },
  {
    id: 18,
    title: "Cutillus Corammand",
    description:
      'Cutillus Coramand, the indomitable captain of the infamous vessel "Empty Hand," casts a foreboding shadow upon the treacherous seas. Known far and wide for his audacious exploits and his merciless pursuit of ill-gotten gains, his name strikes fear into the hearts of both commoners and crowned heads alike. Legends tell of the ill-fated encounter with King Esleys wounded ship, where his crews greedy ambitions were met with a swift and resounding defeat, forever branding the captain and his ship with the moniker that serves as a haunting reminder of their folly.',
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-cutillus-mihaylov.jpg",
    tools: ["Photoshop", "Procreate"],
    tags: ["Illustration", "Character Design", "Concept Art"],
    additionalImages: [],
  },
  {
    id: 19,
    title: "Sherak Cartographer",
    description:
      "Situated at the very top of Sheraks canopy, amidst the thickets of its giant trees and the nests of the myriad flocks of birds, lies the observatory. In it, a young, seemingly skinny girl spends her days in sleep and her nights in restless and merciless pursuit of the stars. Her eyes half-blind to sunlight, are fully sensitive to moon and starlight, enhancing her vision and filling her being with excitement. She is the cartographer.",
    category: "illustration",
    image:
      "/images/illustration_images/mihail-mihaylov-sherak-cartographer-mihaylov.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design"],
    additionalImages: [
      "/images/illustration_images/mihail-mihaylov-sherak-cartographer-mihaylov-gray.jpg",
    ],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 20,
    title: "Yrein the Beer Maiden",
    description:
      "In the taverns of Beer, the tales of Yrein, the maiden of unmatched might, echo through the hallowed halls. With her towering presence and a cascade of golden locks, she stands as the firstborn amidst a rowdy brood of seven. A sellsword of unrivaled prowess, her every move exudes a tremendous grace that commands respect, shattering armor with every swing of her gleaming blade.",
    category: "illustration",
    image:
      "/images/illustration_images/mihail-mihaylov-yrein-splash-mihaylov.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design"],
    additionalImages: [
      "/images/illustration_images/mihail-mihaylov-yrein-concept-mihaylov.jpg",
    ],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 21,
    title: "Atzi",
    description:
      "A few concepts and a finished character I did for Mini Golf 3D City Stars Arcade. The character is heavily inspired by Aztec culture and their traditional costumes.",
    category: "illustration",
    image:
      "/images/illustration_images/mihail-mihaylov-aztec-character-mihaylov.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Game Art"],
    additionalImages: [],
  },
  {
    id: 22,
    title: "Bateman",
    description:
      "A personal project, depicting popular superhero in the aesthetics of eastern Europe.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-bateman.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Fan Art"],
    additionalImages: [],
  },
  {
    id: 23,
    title: "Degir",
    description: 'Degir is a character for the 2D platformer game "Sin".',
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-degir-concepts-02.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Game Art"],
    additionalImages: [
      "/images/illustration_images/mihail-mihaylov-degir-concepts.jpg",
    ],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 24,
    title: "Dragonslayer Fiora",
    description:
      "A Dragonslayer skin for the popular League of Legends character Fiora.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-dragonslayer-fiora.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Fan Art"],
    additionalImages: [],
  },
  {
    id: 25,
    title: "Carrion Bird",
    description:
      "A mythical creature inspired by dark fantasy themes and folklore.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-carrion-bird.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Creature Design"],
    additionalImages: [],
  },
  {
    id: 26,
    title: "Forest Spirit Rhaela",
    description:
      "A forest spirit guardian who protects the ancient woodlands and its creatures.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-rhaela.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Fantasy Art"],
    additionalImages: [],
  },
  {
    id: 27,
    title: "Medieval Food",
    description:
      "A collection of food assets designed for medieval-themed games and projects.",
    category: "illustration",
    image: "/images/illustration_images/vegetable-soup-mihaylov.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Game Asset", "Food Illustration"],
    additionalImages: [
      "/images/illustration_images/baked-ham-mihaylov.jpg",
      "/images/illustration_images/bread-mihaylov.jpg",
      "/images/illustration_images/chicken-leg-mihaylov.jpg",
      "/images/illustration_images/emmental-mihaylov.jpg",
      "/images/illustration_images/mushroom1-mihaylov.jpg",
      "/images/illustration_images/mushroom2-mihaylov.jpg",
      "/images/illustration_images/redmushroom-mihaylov.jpg",
      "/images/illustration_images/red-onion-mihaylov.jpg",
      "/images/illustration_images/steak-mihaylov.jpg",
    ],
    thumbnailDimensions: { height: "100px", width: "100px" },
  },
  {
    id: 28,
    title: "Fantasy Game UI",
    description:
      "Game Settings interface for a fantasy mobile game. Includes a music slider, general sound slider and a close menu button.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-fantasy.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "UI Design", "Game UI"],
    additionalImages: [],
  },
  {
    id: 29,
    title: "Sci-Fi UI",
    description:
      "Game Settings interface for a sci-fi mobile game. Includes a music slider, general sound slider and a close menu button.",
    category: "illustration",
    image: "/images/illustration_images/mihail-mihaylov-sci-fi.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "UI Design", "Game UI"],
    additionalImages: [],
  },
  {
    id: 30,
    title: "Game Textures",
    description:
      "A collection of game textures and items for various gaming environments.",
    category: "illustration",
    image: "/images/illustration_images/animal-textures-mihaylov.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Game Asset", "Textures"],
    additionalImages: [
      "/images/illustration_images/food-textures-mihaylov.jpg",
    ],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 31,
    title: "Frost Mage",
    description:
      "In the eerie depths of Naxxramas necropolis a formidable mage known as Fp the Arcanist harnesses the very essence of frost and shadow. Cloaked in swirling robes adorned with icy crystals, Fp commands an army of frozen horrors, guarding the necropolis with an icy grip. His chilling spells and strategic prowess make him both a guardian and a terror within Naxxramas, a force to be reckoned with for any adventurer daring to step into its frigid heart.",
    category: "illustration",
    image: "/images/illustration_images/fp-mihaylov1.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Fan Art", "WoW"],
    additionalImages: ["/images/illustration_images/fp-mihaylov2.jpg"],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 32,
    title: "Amber Druids Village",
    description:
      "Nestled within the heart of an ancient woodland, the ethereal village of Amberhaven evokes a sense of timelessness, resonant of the most enchanting fantasy realms. Its cobblestone streets wind between quaint cottages adorned with intricate carvings, while the villagers, donned in rich earth-toned attire, practice the art of preserving their departed within luminescent crystals of amber. These shimmering relics, glinting in the sunlight, stand as both memorials to the past and guardians against the encroaching shadows that haunt the fringes of their enchanted realm.",
    category: "illustration",
    image: "/images/illustration_images/amberprison-mihaylov1.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Environment Design", "Game Asset"],
    additionalImages: ["/images/illustration_images/amberprison-mihaylov2.png"],
    thumbnailDimensions: { height: "120px", width: "auto" },
  },
  {
    id: 33,
    title: "Character Doodles",
    description:
      "Various character portraits and concept sketches exploring different styles and personalities.",
    category: "illustration",
    image: "/images/illustration_images/character-doodle1-mihaylov.jpg",
    tools: ["Photoshop"],
    tags: ["Illustration", "Character Design", "Concept Art"],
    additionalImages: [
      "/images/illustration_images/character-doodle2-mihaylov.jpg",
      "/images/illustration_images/character-doodle3-mihaylov.jpg",
      "/images/illustration_images/character-doodle4-mihaylov.jpg",
      "/images/illustration_images/character-doodle5-mihaylov.jpg",
      "/images/illustration_images/character-doodle6-mihaylov.jpg",
      "/images/illustration_images/character-doodle7-mihaylov.jpg",
    ],
    thumbnailDimensions: { height: "100px", width: "auto" },
  },
  {
    id: 34,
    title: "Asfalting Ltd",
    description:
      "Modern website for a road construction and maintenance company.",
    category: "development",
    image: "/images/development_images/asfaltingltd-1.webp",
    tools: ["React", "Javascript", "Styled Components", "Figma"],
    tags: ["React", "Web Design", "Concept Art"],
    link: "https://asfaltingltd.netlify.app/",
    additionalImages: [
      "/images/development_images/asfaltingltd-2.webp",
      "/images/development_images/asfaltingltd-3.webp",
    ],
    thumbnailDimensions: { height: "100px", width: "auto" },
  },
];

export default projects;
